### teste de login ### 

POST http://localhost:4000/login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "senha": "admin"
}

### teste de buscar todas os motoristasVeiculos 

GET http://localhost:4000/entregas HTTP/1.1
content-type: application/json

### teste de buscar motoristaVeiculo por ID 
GET http://localhost:4000/entregas/de518b6a-a8da-4f9e-98a0-31a6847c1274 HTTP/1.1
content-type: application/json


### teste de inserção de motoristaVeiculo ### 
POST http://localhost:4000/entregas HTTP/1.1
content-type: application/json

{
    "descricao": "descricaoTestVeicu",
    "dataInicio": "2024-01-01",
    "dataEntrega": "2024-01-01",
    "motorisVeiculoId": "96ce250c-e468-442c-b02d-48c40cbad084", 
    "clienteID": "07198b6c-217c-4b0b-a93a-55c3a2659f53"
}

### teste de atualização de motoristaVeiculo 

PUT http://localhost:4000/entregas/de518b6a-a8da-4f9e-98a0-31a6847c1274 HTTP/1.1
Content-Type: application/json

{
    "descricao": "descricaoTestVeicuMod",
    "dataInicio": "2024-01-02",
    "dataEntrega": "2024-01-02",
    "motorisVeiculoId": "96ce250c-e468-442c-b02d-48c40cbad084", 
    "clienteID": "07198b6c-217c-4b0b-a93a-55c3a2659f53"

}

### teste de exclusão de motoristaVeiculo 
DELETE http://localhost:4000/entregas/e249f9e6-c408-403a-b5c5-c0896e49482b HTTP/1.1
content-type: application/json

{

}
