### teste de login ###
POST http://localhost:4000/Login HTTP/1.1
content-type: application/json

{
    "login": "admin",
    "senha": "admin"
}


### teste de buscar todas as contas ###
GET http://localhost:4000/contas HTTP/1.1
content-type: application/json


### teste de buscar conta por ID ###
GET http://localhost:4000/contas/e356a463-f333-4102-a1a5-c380b7360b90 HTTP/1.1
content-type: application/json


### teste de inserção de conta ###

POST http://localhost:4000/contas HTTP/1.1
content-type: application/json

{
    "descricao": "Conta do felipe",
    "tipo": "Despesa",
    "valor": 150.00,
    "data": "2024-11-13",
    "status": "Pendente",
    "forma_pagamento": "Cartão de crédito",
    "usuario_id": "e4acfa25-9943-40cf-8612-c97144e41bd8"

}

### teste de atualização de conta ###
Put http://localhost:4000/UpdateConta/e356a463-f333-4102-a1a5-c380b7360b90 HTTP/1.1
content-type: application/json


{
    "descricao": "Conta de luz atualizada kkkkkkkkkkkkk",
    "tipo": "Despesa",
    "valor": 160.00,
    "data": "2024-11-14",
    "status": "Paga",
    "forma_pagamento": "Débito",
    "usuario_id":"f9ad9a44-bf41-4c64-ba34-0e21bb162c78"
}

### teste de exclusão de conta ###
delete http://localhost:4000/DeleteConta/dfd1dece-67e6-4486-b46d-cf3440239afa HTTP/1.1
content-type: application/json

